import { User } from './types';

export const DEMO_USERS: Record<string, User & { password: string }> = {
  'ceo.office@jcf.local': {
    id: '1',
    email: 'ceo.office@jcf.local',
    password: 'ceo123',
    firstName: 'CEO',
    lastName: 'Office',
    department: 'ceo-office',
    role: 'ceo',
  },
  'hr@jcf.local': {
    id: '2',
    email: 'hr@jcf.local',
    password: 'hr123',
    firstName: 'HR',
    lastName: 'Manager',
    department: 'hr',
    role: 'hr_pod_lead',
  },
  'psyconnect@jcf.local': {
    id: '3',
    email: 'psyconnect@jcf.local',
    password: 'psy123',
    firstName: 'Psy',
    lastName: 'Connect',
    department: 'psy-connect',
    role: 'member',
  },
  'tech@jcf.local': {
    id: '4',
    email: 'tech@jcf.local',
    password: 'tech123',
    firstName: 'Tech',
    lastName: 'Lead',
    department: 'tech',
    role: 'department_pod_lead',
  },
  'pr@jcf.local': {
    id: '5',
    email: 'pr@jcf.local',
    password: 'pr123',
    firstName: 'PR',
    lastName: 'Manager',
    department: 'pr',
    role: 'member',
  },
  'carcinoma@jcf.local': {
    id: '6',
    email: 'carcinoma@jcf.local',
    password: 'car123',
    firstName: 'Carcinoma',
    lastName: 'Specialist',
    department: 'carcinoma',
    role: 'member',
  },
  'medical@jcf.local': {
    id: '7',
    email: 'medical@jcf.local',
    password: 'medical123',
    firstName: 'Medical',
    lastName: 'Partnership',
    department: 'medical-partnership',
    role: 'member',
  },
  'cgmp@jcf.local': {
    id: '8',
    email: 'cgmp@jcf.local',
    password: 'cgmp123',
    firstName: 'CGMP',
    lastName: 'Manager',
    department: 'cgmp',
    role: 'member',
  },
};
